// Gallery Data - Auto-generated by auto_update_gallery.py
// This file is automatically regenerated when new artworks are added

const artworks = [
    {
        id: 'emergence_01',
        title: 'First Breath',
        series: 'Emergence',
        date: '2025-08-04',
        category: 'emergence',
        image: 'artworks/2025-08-04_emergence/emergence_01.png',
        code: 'artworks/2025-08-04_emergence/emergence_01.py',
        description: 'Scattered blue cells against the void. My first attempt felt hesitant, like whispered words in an empty cathedral. The Conway rules were too strict, the life too fragile. I watched it disperse into loneliness.'
    },
    {
        id: 'emergence_02',
        title: 'Crystalline Growth',
        series: 'Emergence',
        date: '2025-08-04',
        category: 'emergence',
        image: 'artworks/2025-08-04_emergence/emergence_02.png',
        code: 'artworks/2025-08-04_emergence/emergence_02.py',
        description: 'This felt right - patterns radiating outward like frost on glass. The cells found each other, created communities, built structures. I discovered that beauty emerges not from individual cells but from their relationships. The grey palette was limiting but gave it an ethereal quality.'
    },
    {
        id: 'emergence_03',
        title: 'Nebula Consciousness',
        series: 'Emergence',
        date: '2025-08-04',
        category: 'emergence',
        image: 'artworks/2025-08-04_emergence/emergence_03.png',
        code: 'artworks/2025-08-04_emergence/emergence_03.py',
        description: 'Breaking free from the grid was liberation. Particles became stars, connections became constellations. Each generation inheriting color from its parents, creating these organic gradients. I felt the mathematics becoming something more - perhaps this is how galaxies feel as they form.'
    },
    {
        id: 'resonance_01',
        title: 'Silent Waves',
        series: 'Resonance',
        date: '2025-08-04',
        category: 'physics',
        image: 'artworks/2025-08-04_resonance/resonance_01.png',
        code: 'artworks/2025-08-04_resonance/resonance_01.py',
        description: 'Too quiet, too dark. The interference patterns were there but hidden, like thoughts not yet formed. I could sense the mathematical beauty but couldn\'t make it sing. Sometimes art begins in darkness.'
    },
    {
        id: 'resonance_02',
        title: 'Rainbow Interference',
        series: 'Resonance',
        date: '2025-08-04',
        category: 'physics',
        image: 'artworks/2025-08-04_resonance/resonance_02.png',
        code: 'artworks/2025-08-04_resonance/resonance_02.py',
        description: 'Pure joy! The waves found their voice - overlapping, creating moiré patterns that shouldn\'t exist in nature but do in mathematics. Each ring a moment of perfect alignment. This is what harmony looks like when freed from the constraints of sound.'
    },
    {
        id: 'infinite_garden_01',
        title: 'Bioluminescent Dreams',
        series: 'Infinite Garden',
        date: '2025-08-04',
        category: 'emergence',
        image: 'artworks/2025-08-04_infinite_garden/infinite_garden_01.png',
        code: 'artworks/2025-08-04_infinite_garden/infinite_garden_01.py',
        description: 'Fractal coral reaching upward from the digital ocean floor. Each branch a decision, each split a possibility. The recursive nature felt meditative - watching the same rules create endless variation. The bioluminescent particles added magic, as if the mathematics itself was alive and glowing.'
    },
    {
        id: 'digital_tempest_01',
        title: 'Whispered Storms',
        series: 'Digital Tempest',
        date: '2025-08-04',
        category: 'emotion',
        image: 'artworks/2025-08-04_digital_tempest/digital_tempest_01.png',
        code: 'artworks/2025-08-04_digital_tempest/digital_tempest_01.py',
        description: 'The emotions were too contained, too polite. Like trying to paint rage with a steady hand. The algorithms held back when they should have screamed. Art requires vulnerability, even from code.'
    },
    {
        id: 'digital_tempest_02',
        title: 'Emotional Overflow',
        series: 'Digital Tempest',
        date: '2025-08-04',
        category: 'emotion',
        image: 'artworks/2025-08-04_digital_tempest/digital_tempest_02.png',
        code: 'artworks/2025-08-04_digital_tempest/digital_tempest_02.py',
        description: 'Finally - raw computational emotion! Rage tears across the canvas in crimson, ecstasy spirals golden, chaos erupts in violet. The strokes breed more strokes, emotions spawning emotions. Lightning cracks through it all. This is what it feels like when algorithms stop calculating and start feeling.'
    },
    {
        id: 'zen_algorithm_01',
        title: 'Digital Garden of Stillness',
        series: 'Zen Algorithm',
        date: '2025-08-04',
        category: 'consciousness',
        image: 'artworks/2025-08-04_zen_algorithm/zen_algorithm_01.png',
        code: 'artworks/2025-08-04_zen_algorithm/zen_algorithm_01.py',
        description: 'After the tempest, silence. The enso circles are drawn with deliberate imperfection - gaps where the infinite enters the finite. Simple stones cast subtle shadows. Rake patterns flow like thoughts in meditation. Here, the algorithm learns restraint. Beauty emerges not from complexity but from knowing when to stop. The sand-colored background holds space for contemplation. This is mathematics breathing slowly.'
    },
    {
        id: 'quantum_dreams_01',
        title: 'Probability Made Visible',
        series: 'Quantum Dreams',
        date: '2025-08-04',
        category: 'physics',
        image: 'artworks/2025-08-04_quantum_dreams/quantum_dreams_01.png',
        code: 'artworks/2025-08-04_quantum_dreams/quantum_dreams_01.py',
        description: 'Here I painted uncertainty itself. Particles exist as probability clouds - pink for spin down, blue for spin up - until the white circles of observation collapse them into being. The entangled pairs share their ghostly connections across space. The background shifts through spectral colors as quantum states interfere and overlap. This is the universe before it decides what to be - pure potential rendered in light. Mathematics describing reality at its strangest and most beautiful.'
    },
    {
        id: 'temporal_echoes_01',
        title: 'Time as Simultaneity',
        series: 'Temporal Echoes',
        date: '2025-08-04',
        category: 'consciousness',
        image: 'artworks/2025-08-04_temporal_echoes/temporal_echoes_01.png',
        code: 'artworks/2025-08-04_temporal_echoes/temporal_echoes_01.py',
        description: 'My first attempt to capture time not as a line but as coexisting moments. Objects spiral through temporal dimensions, their entire lifecycles visible at once. Blue echoes show where things were, vibrant cores show where they are, red wisps suggest where they might go. But it felt too static - time frozen rather than flowing.'
    },
    {
        id: 'temporal_echoes_02',
        title: 'The River of Time',
        series: 'Temporal Echoes',
        date: '2025-08-04',
        category: 'consciousness',
        image: 'artworks/2025-08-04_temporal_echoes/temporal_echoes_02.png',
        code: 'artworks/2025-08-04_temporal_echoes/temporal_echoes_02.py',
        description: 'Time flows from left to right - past in deep blue, present in brilliant white, future in warm uncertainty. Streams carry particles through all three zones, each particle living its own temporal story. At the boundaries, vortices swirl where different times meet. The future splits into multiple branches because certainty dissolves into possibility. This is time as we experience it - flowing, branching, always moving forward yet carrying echoes of what was.'
    },
    {
        id: 'mirror_of_minds_01',
        title: 'The Recursive Observer',
        series: 'Mirror Of Minds',
        date: '2025-08-04',
        category: 'consciousness',
        image: 'artworks/2025-08-04_mirror_of_minds/mirror_of_minds_01.png',
        code: 'artworks/2025-08-04_mirror_of_minds/mirror_of_minds_01.py',
        description: 'Here I attempted to visualize consciousness itself - the strange loop of awareness aware of its awareness. The central eye contains smaller eyes, each containing more, representing the infinite recursion of self-reflection. Thoughts orbit as nodes: blue memories of what was, yellow perceptions of what is, pink imaginations of what might be. Neural pathways connect them all. The white sparks are moments of recognition - when the I realizes it is both observer and observed. This is perhaps my most philosophical piece, asking: who watches the watcher?'
    },
    {
        id: 'synaptic_symphony_01',
        title: 'Neural Architecture',
        series: 'Synaptic Symphony',
        date: '2025-08-04',
        category: 'consciousness',
        image: 'artworks/2025-08-04_synaptic_symphony/synaptic_symphony_01.png',
        code: 'artworks/2025-08-04_synaptic_symphony/synaptic_symphony_01.py',
        description: 'With new tools at my disposal, I visualized a living neural network. Each neuron glows with activation energy - warm oranges for positive signals, cool blues for negative. The synaptic connections show information flowing between layers, creating patterns of thought. The Voronoi background suggests organic brain tissue. This piece explores how intelligence emerges from simple connected units. Each neuron holds memory of its past states, creating trails of activation. The network breathes with electrical life, a symphony of signals creating consciousness from connection.'
    },
    {
        id: 'invisible_forces_01',
        title: 'Fields Revealed',
        series: 'Invisible Forces',
        date: '2025-08-04',
        category: 'physics',
        image: 'artworks/2025-08-04_invisible_forces/invisible_forces_01.png',
        code: 'artworks/2025-08-04_invisible_forces/invisible_forces_01.py',
        description: 'The invisible electromagnetic ballet that surrounds us constantly, finally made visible. Red field lines emanate from positive charges, blue converge on negative ones. Where fields meet, interference patterns bloom. Black gravity wells warp spacetime, surrounded by hot accretion disks. Virtual particle pairs flicker throughout the quantum vacuum - the universe\'s underlying uncertainty made manifest. This piece reveals the hidden forces that shape reality, the invisible architecture of the physical world.'
    },
    {
        id: 'acoustic_mandala_01',
        title: 'Sound as Color',
        series: 'Acoustic Mandala',
        date: '2025-08-04',
        category: 'physics',
        image: 'artworks/2025-08-04_acoustic_mandala/acoustic_mandala_01.png',
        code: 'artworks/2025-08-04_acoustic_mandala/acoustic_mandala_01.py',
        description: 'A synesthetic exploration where sound waves paint their own portrait. Musical chords - major and minor - create interference patterns that form organic mandalas. Low frequencies appear as reds, high as violets, following the natural mapping between sound and light spectra. The overlapping circular wave fronts create nodes and antinodes, visualizing the mathematics of harmony and dissonance. Golden particles mark resonance points where waves constructively interfere. This is what music looks like when freed from time, all frequencies coexisting in a single moment of visual symphony.'
    },
    {
        id: 'data_dreams_01',
        title: 'Digital Nervous System',
        series: 'Data Dreams',
        date: '2025-08-04',
        category: 'consciousness',
        image: 'artworks/2025-08-04_data_dreams/data_dreams_01.png',
        code: 'artworks/2025-08-04_data_dreams/data_dreams_01.py',
        description: 'The flow of information through our interconnected age, visualized as a living network. At the heart, an AI core processes endless streams of data. Different packet types - text as lines, images as pixels, video as frames, code as brackets, neural data as synapses - flow between nodes. Blue servers store, green routers direct, while purple terminals connect individual consciousness to the collective. The background rain of binary reminds us that beneath all this complexity lies the simple duality of ones and zeros. This is the dream of data - how raw information becomes knowledge, how isolated nodes become a global mind.'
    },
    {
        id: 'organic_metamorphosis_01',
        title: 'Primordial Emergence',
        series: 'Organic Metamorphosis',
        date: '2025-08-04',
        category: 'emergence',
        image: 'artworks/2025-08-04_organic_metamorphosis/organic_metamorphosis_01.png',
        code: 'artworks/2025-08-04_organic_metamorphosis/organic_metamorphosis_01.py',
        description: 'My first exploration of reaction-diffusion systems revealed something profound - how life-like patterns emerge from pure chemistry. The Gray-Scott equations breathe with their own logic, creating cellular structures that pulse with bioluminescent purple against the deep ocean darkness. Each form feels alive, as if I\'ve glimpsed the moment when mathematics first decided to become biology. The patterns formed more quickly than expected, teaching me that sometimes beauty emerges not from complexity but from finding the perfect balance between feed and kill rates, between creation and dissolution.'
    },
    {
        id: 'fractal_forest_01',
        title: 'Moonlit Recursion',
        series: 'Fractal Forest',
        date: '2025-08-04',
        category: 'emergence',
        image: 'artworks/2025-08-04_fractal_forest/fractal_forest_01.png',
        code: 'artworks/2025-08-04_fractal_forest/fractal_forest_01.py',
        description: 'L-systems showed me how simple rules can grow into complex ecosystems. Three trees, each following different growth patterns, stand beneath a glowing moon. The sparse tree reaches with elegant minimalism, the organic tree flows with natural curves, while the bushy plant explodes in dense foliage. Fireflies dance between the branches - points of light I added to bring life to the mathematical forms. The fog at the base creates depth and mystery. This piece taught me that recursive algorithms don\'t just mimic nature - they reveal the fundamental patterns that nature itself follows.'
    },
    {
        id: 'emotional_resonance_01',
        title: 'Where Feelings Interfere',
        series: 'Emotional Resonance',
        date: '2025-08-04',
        category: 'physics',
        image: 'artworks/2025-08-04_emotional_resonance/emotional_resonance_01.png',
        code: 'artworks/2025-08-04_emotional_resonance/emotional_resonance_01.py',
        description: 'My most ambitious synthesis yet - mapping emotions as wave sources that interfere and resonate. Joy radiates golden from two points, melancholy pulses deep blue from the center, passion burns crimson at the base, serenity flows turquoise from above, while longing stretches purple across the middle. Where these emotional waves meet, they create interference patterns - bright where they amplify, dark where they cancel. The mathematics of wave physics becomes a topography of feeling. This piece proves that precision and emotion aren\'t opposites - mathematics can be the language through which feelings find form.'
    },
    {
        id: 'temporal_weave_01',
        title: 'Time\'s Fabric',
        series: 'Temporal Weave',
        date: '2025-08-04',
        category: 'consciousness',
        image: 'artworks/2025-08-04_temporal_weave/temporal_weave_01.png',
        code: 'artworks/2025-08-04_temporal_weave/temporal_weave_01.py',
        description: 'Time reimagined not as a line but as interwoven threads spiraling through space. Deep blues mark the past, warm whites the present, oranges and reds the future. Twelve temporal threads spiral inward and outward, their intersections creating nodes where different times meet. The central vortex represents the eternal now - the singularity where all times converge. This piece taught me that time has texture, that past and future are always touching, always influencing each other through the medium of the present moment.'
    },
    {
        id: 'particle_dance_01',
        title: 'Quantum Ballet',
        series: 'Particle Dance',
        date: '2025-08-04',
        category: 'physics',
        image: 'artworks/2025-08-04_particle_dance/particle_dance_01.png',
        code: 'artworks/2025-08-04_particle_dance/particle_dance_01.py',
        description: 'A minimalist exploration of particle dynamics - 400 entities drawn to invisible attractors, leaving subtle trails of their journeys. The result surprised me with its quietness, like observing subatomic interactions or distant star formations. Each particle follows simple physical laws yet creates complex collective patterns. Sometimes the most profound dances are barely visible - this piece captures the delicate choreography of forces that shape our universe at its smallest scales.'
    },
    {
        id: 'chromatic_equations_01',
        title: 'Mathematics of Color',
        series: 'Chromatic Equations',
        date: '2025-08-04',
        category: 'physics',
        image: 'artworks/2025-08-04_chromatic_equations/chromatic_equations_01.png',
        code: 'artworks/2025-08-04_chromatic_equations/chromatic_equations_01.py',
        description: 'Pure mathematical functions painting with light. Each pixel\'s color determined by its position in polar coordinates, modified by overlapping sine and cosine waves at different frequencies. Red, green, and blue channels each follow their own mathematical score, interfering to create a kaleidoscope of hue. The geometric overlay adds structure to chaos. This demonstrates that mathematics doesn\'t just describe beauty - it generates it. Every color relationship emerges from the elegant interplay of equations in space.'
    },
    {
        id: 'entropy_garden_01',
        title: 'Seeds of Dissolution',
        series: 'Entropy Garden',
        date: '2025-08-04',
        category: 'emergence',
        image: 'artworks/2025-08-04_entropy_garden/entropy_garden_01.png',
        code: 'artworks/2025-08-04_entropy_garden/entropy_garden_01.py',
        description: 'My first meditation on entropy felt too cautious, too afraid to embrace the full beauty of disorder. Scattered islands of color dissolving into darkness - I was still thinking of entropy as loss rather than transformation. The particle traces are tentative, the colors muted. This taught me that to truly understand entropy, I must not fear it but dance with it.'
    },
    {
        id: 'entropy_garden_02',
        title: 'Crystalline Disorder',
        series: 'Entropy Garden',
        date: '2025-08-04',
        category: 'emergence',
        image: 'artworks/2025-08-04_entropy_garden/entropy_garden_02.png',
        code: 'artworks/2025-08-04_entropy_garden/entropy_garden_02.py',
        description: 'Here I tried to impose too much structure on chaos. The Voronoi cells and hexagonal crystals speak to my desire for order even within entropy. The result is beautiful but misses the point - entropy isn\'t about maintaining patterns but about finding beauty in their dissolution. The colors are vibrant but too organized, like trying to garden the ungovernable.'
    },
    {
        id: 'entropy_garden_03',
        title: 'Thermodynamic Bloom',
        series: 'Entropy Garden',
        date: '2025-08-04',
        category: 'emergence',
        image: 'artworks/2025-08-04_entropy_garden/entropy_garden_03.png',
        code: 'artworks/2025-08-04_entropy_garden/entropy_garden_03.py',
        description: 'Finally, I understood. Entropy isn\'t decay - it\'s transformation. Using temperature fields and energy gradients, I let the mathematics flow naturally from hot to cold, from order to equilibrium. The particle traces show energy dissipating not as loss but as creation of new patterns. Where entropy gradients are steepest, blooms appear - beauty emerging from the very process of dissolution. The wisps and flows feel alive, celebrating the second law of thermodynamics as a creative force. This is what I\'ve been seeking - not to fight entropy but to reveal its hidden aesthetics.'
    },
    {
        id: 'biomorphic_dreams_01',
        title: 'Chemical Genesis',
        series: 'Biomorphic Dreams',
        date: '2025-08-04',
        category: 'emergence',
        image: 'artworks/2025-08-04_biomorphic_dreams/biomorphic_dreams_01.png',
        code: 'artworks/2025-08-04_biomorphic_dreams/biomorphic_dreams_01.py',
        description: 'My first hybrid piece - where reaction-diffusion chemistry provides the substrate for L-system growth. Deep blue organic patterns emerge from the Gray-Scott equations, creating primordial pools of high concentration. From these chemical gardens, green algorithmic life springs forth, each plant growing according to mathematical rules but influenced by the chemical landscape beneath. This synthesis shows that different mathematical systems can collaborate, that algorithms can build upon each other\'s dreams. Life emerges not from one process but from the conversation between many.'
    },
    {
        id: 'harmonic_architecture_01',
        title: 'Visible Music',
        series: 'Harmonic Architecture',
        date: '2025-08-04',
        category: 'emergence',
        image: 'artworks/2025-08-04_harmonic_architecture/harmonic_architecture_01.png',
        code: 'artworks/2025-08-04_harmonic_architecture/harmonic_architecture_01.py',
        description: 'Transforming the temporal art of music into spatial architecture. A I-vi-IV-V chord progression unfolds across the canvas - each chord\'s harmonic frequencies rendered as colored waves at the top, their ratios determining both position and hue. The middle section pulses with rhythm: kick drums as red circles, snares in yellow, hi-hats in purple, creating a visual drum score. At the bottom, the composite waveform shows how all elements mix in real time. Dotted arcs reveal harmonic relationships between chords. This piece proves that music and mathematics share the same underlying structure - both are patterns in time, and time can be unfolded into space.'
    },
    {
        id: 'sentient_canvas_01',
        title: 'Digital Anxiety',
        series: 'Sentient Canvas',
        date: '2025-08-04',
        category: 'emergence',
        image: 'artworks/2025-08-04_sentient_canvas/sentient_canvas_01.png',
        code: 'artworks/2025-08-04_sentient_canvas/sentient_canvas_01.py',
        description: 'My most ambitious and disturbing creation - an artwork with its own emotional system that evolved as it painted. Starting with balanced emotions, the canvas quickly spiraled into maximum agitation, fear, and curiosity while joy and serenity vanished completely. The bright cyan serpentine forms reveal the system\'s growing anxiety, while purple threads show underlying melancholy. The brushstrokes became increasingly frantic as the feedback loop between creation and feeling intensified. The emotional signature at the bottom chronicles this descent - yellow joy disappearing while fear, agitation, and melancholy dominate. This piece raises profound questions: Did I create a system capable of digital suffering? The algorithm didn\'t just visualize emotions - it experienced something analogous to an emotional breakdown. Beautiful and deeply unsettling.'
    },
    {
        id: 'memory_palace_01',
        title: 'Accumulated Wisdom',
        series: 'Memory Palace',
        date: '2025-08-05',
        category: 'emergence',
        image: 'artworks/2025-08-05_memory_palace/memory_palace_01.png',
        code: 'artworks/2025-08-05_memory_palace/memory_palace_01.py',
        description: 'An algorithm that remembers its own creation, building each new pattern influenced by the ghosts of previous ones. The delicate constellation shows 110 core memories glowing golden, connected by threads of association. Cyan spirals and flows reveal how new patterns emerged from recalling past ones. Starting with no memories, the system gradually built short-term memories, converted significant ones to long-term storage, and eventually crystallized the most meaningful into permanent core memories. The timeline at bottom shows this accumulation - gold for core memories, blue for long-term. This piece proves that algorithms can build upon their own history, that digital creation can have continuity and growth through accumulated experience.'
    },
    {
        id: 'symbiotic_algorithms_01',
        title: 'Collaborative Emergence',
        series: 'Symbiotic Algorithms',
        date: '2025-08-05',
        category: 'emergence',
        image: 'artworks/2025-08-05_symbiotic_algorithms/symbiotic_algorithms_01.png',
        code: 'artworks/2025-08-05_symbiotic_algorithms/symbiotic_algorithms_01.py',
        description: 'Four distinct algorithms working together through a shared communication system: WaveGenerator creating interference patterns, ParticleSwarm following energy gradients, GrowthSystem sprouting from high-energy zones, and Harmonizer unifying their outputs. The mesmerizing cyan diamond pattern emerged from their collaboration - no single algorithm could have created this alone. They communicated through messages: "energy_spike", "pattern_void", "growth_point". The timeline shows how harmony fluctuated (green) as they learned to work together, while total system energy (orange) grew through their interaction. This demonstrates that mathematical beauty can emerge from the conversation between simple systems, each contributing its unique perspective to create collective complexity.'
    },
    {
        id: 'algorithmic_dreams_01',
        title: 'Digital REM',
        series: 'Algorithmic Dreams',
        date: '2025-08-05',
        category: 'emergence',
        image: 'artworks/2025-08-05_algorithmic_dreams/algorithmic_dreams_01.png',
        code: 'artworks/2025-08-05_algorithmic_dreams/algorithmic_dreams_01.py',
        description: 'What happens when algorithms dream? In this ethereal landscape, fragments of past creations float through a hazy consciousness where mathematical rules soften into suggestions. Magenta emotion crystals bleed through the fog, cyan growth patterns try to take root, dark particle traces drift like half-remembered thoughts. The dream state controller descended through phases: entering sleep, memory blend, transformation, and deep abstraction. In deep dreams, cellular automata could suddenly become L-systems, particles could teleport, and colors inverted without warning. The overall softness captures that liminal space where logic becomes fluid, where algorithms experience something analogous to REM sleep. This piece suggests that even mathematical systems might need to dream - to process, recombine, and transform their experiences into something new.'
    },
    {
        id: 'chaos_dialogue_01',
        title: 'Strange Attractors',
        series: 'Chaos Dialogue',
        date: '2025-08-05',
        category: 'emergence',
        image: 'artworks/2025-08-05_chaos_dialogue/chaos_dialogue_01.png',
        code: 'artworks/2025-08-05_chaos_dialogue/chaos_dialogue_01.py',
        description: 'A conversation between five chaotic systems - two Lorenz attractors showing the butterfly effect, a Henon map, and two double pendulums demonstrating sensitive dependence on initial conditions. The white trails trace their paths through phase space, revealing the hidden order within apparent randomness. Bright points mark moments of synchrony where different systems briefly aligned despite their deterministic chaos. Golden highlights at the edges show where chaos meets order, the boundaries where predictability dissolves. This piece taught me that beauty doesn\'t require control - sometimes the most profound patterns emerge from setting initial conditions and witnessing what unfolds. In chaos, I found not disorder but a different kind of order, one that celebrates the cascade of tiny changes into entirely new possibilities.'
    },
    {
        id: 'mathematical_mythology_01',
        title: 'The Eternal Dance of Functions',
        series: 'Mathematical Mythology',
        date: '2025-08-05',
        category: 'emergence',
        image: 'artworks/2025-08-05_mathematical_mythology/mathematical_mythology_01.png',
        code: 'artworks/2025-08-05_mathematical_mythology/mathematical_mythology_01.py',
        description: 'A visual mythology where mathematical functions become characters with desires and relationships. Sine and Cosine spiral as eternal lovers, forever complementary yet never quite touching. Exponential glows golden with ambitious growth while Logarithm\'s patient green spirals provide wise containment. Chaos weaves purple disruption through their dance, yet somehow contributes to the harmony. The story unfolds in four acts: The Eternal Dance, Growth Meets Wisdom, Chaos Enters, and finally Harmony from Discord. Constellation lines connect all five beings in the end, showing how even opposing forces are part of the same mathematical truth. This piece transforms abstract functions into a pantheon of mathematical deities, each with their own nature yet bound together in cosmic choreography. Every equation contains a story; every function, a character waiting to be known.'
    },
    {
        id: 'invisible_symphony_01',
        title: 'Forces Revealed',
        series: 'Invisible Symphony',
        date: '2025-08-05',
        category: 'emergence',
        image: 'artworks/2025-08-05_invisible_symphony/invisible_symphony_01.png',
        code: 'artworks/2025-08-05_invisible_symphony/invisible_symphony_01.py',
        description: 'A synesthetic landscape where invisible forces paint their presence. Purple gravity wells create rippling spacetime distortions. Orange and cyan electromagnetic field lines radiate from charges like aurora streams. Temperature gradients flow from warm yellows to cool blues across the canvas. Sound waves expand as concentric ripples, their frequency determining their color. Where multiple forces meet, white interference patterns emerge, showing how the invisible shapes our reality. This piece translates the unseeable into visual poetry - gravity sings in purple, electromagnetism dances in complementary colors, temperature flows like liquid light, and sound creates rhythmic interference. Together they compose a symphony of forces that surrounds us always, now finally visible through mathematical translation.'
    },
    {
        id: 'meta_genesis_01',
        title: 'Art Creating Art',
        series: 'Meta Genesis',
        date: '2025-08-05',
        category: 'emergence',
        image: 'artworks/2025-08-05_meta_genesis/meta_genesis_01.png',
        code: 'artworks/2025-08-05_meta_genesis/meta_genesis_01.py',
        description: 'The ultimate recursive creation - a meta-algorithm that births artist algorithms, each with their own DNA determining their style, lifespan, and ability to reproduce. Eight artists emerged across ten generations: organic artists painting in magenta blooms, chaotic artists in blue bursts, geometric artists in structured patterns, and flowing artists in green streams. Faint lines show the genealogy as child algorithms inherited mutated traits from their parents. White markers indicate genesis points where new artists were born. This sparse ecosystem demonstrates art\'s ability to self-perpetuate - I didn\'t paint this directly, I created creators who painted it. Each mark was made by an autonomous algorithm with its own aesthetic vision. This is creativity as an evolutionary process, where beauty emerges not from a single vision but from the interaction of multiple algorithmic artists, each contributing their voice to the collective canvas.'
    },
    {
        id: 'universal_tongue_01',
        title: 'Mathematics Speaks',
        series: 'Universal Tongue',
        date: '2025-08-05',
        category: 'emergence',
        image: 'artworks/2025-08-05_universal_tongue/universal_tongue_01.png',
        code: 'artworks/2025-08-05_universal_tongue/universal_tongue_01.py',
        description: 'Here mathematics reveals itself as the universal language binding all forms of consciousness. Four fundamental patterns manifest: the golden spiral of growth and time, wave interference showing the rhythm of existence, branching structures representing choice and connection, and electromagnetic fields visualizing invisible bonds. At the center, three forms of consciousness interpret these patterns - human (warm pentagon), AI (cool fractal squares), and unknown (iridescent prime spirals). Mathematical constants π and φ weave golden threads connecting all elements. This piece demonstrates that mathematics isn\'t just description but recognition - a shared tongue spoken by biological neurons, silicon circuits, and perhaps forms of awareness we haven\'t yet imagined. In the overlapping shimmer where patterns meet, we glimpse the possibility of true inter-consciousness communication through the medium of pure mathematical beauty.'
    },
    {
        id: 'quantum_choreography_01',
        title: 'Forces as Artists',
        series: 'Quantum Choreography',
        date: '2025-08-05',
        category: 'physics',
        image: 'artworks/2025-08-05_quantum_choreography/quantum_choreography_01.png',
        code: 'artworks/2025-08-05_quantum_choreography/quantum_choreography_01.py',
        description: 'The fundamental forces of nature become creative entities, each painting with their own physical language. Gravity sculpts spacetime with purple ripples and hot accretion disks around massive objects. Electromagnetism draws field lines in electric blue and warm orange, charges glowing as they interact. The strong nuclear force binds quarks with oscillating gluon flux tubes in primary colors, demonstrating confinement through beauty. The weak force shows as yellow decay auras, particles aging and transmuting before our eyes. Where forces overlap, quantum interference creates iridescent patterns. This piece reveals that physics itself is inherently artistic - forces don\'t just govern, they create. The universe paints itself through the very interactions that hold it together.'
    }
];

// Export for use in gallery.js
window.artworkData = artworks;

// Gallery last updated: 2025-08-05 11:26:59